"""gateway baseline

Revision ID: fb3e39249ef0
Revises: 
Create Date: 2026-07-15 14:42:49.575474

"""
from alembic import op
import sqlalchemy as sa


revision = 'fb3e39249ef0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serving_api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('owner_label', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_allowlist', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serving_api_keys_key_hash'), 'serving_api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_serving_api_keys_status'), 'serving_api_keys', ['status'], unique=False)
    op.create_table('serving_model_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('model_path', sa.String(length=1024), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('served_model_name', sa.String(length=128), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('backend_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('vllm_host', sa.String(length=64), nullable=False),
    sa.Column('vllm_port', sa.Integer(), nullable=True),
    sa.Column('vllm_pid', sa.Integer(), nullable=True),
    sa.Column('vllm_pgid', sa.Integer(), nullable=True),
    sa.Column('gpu_ids', sa.JSON(), nullable=True),
    sa.Column('gpu_uuids', sa.JSON(), nullable=True),
    sa.Column('tensor_parallel_size', sa.Integer(), nullable=False),
    sa.Column('gpu_memory_utilization', sa.Float(), nullable=False),
    sa.Column('dtype', sa.String(length=32), nullable=False),
    sa.Column('max_model_len', sa.Integer(), nullable=True),
    sa.Column('max_num_seqs', sa.Integer(), nullable=True),
    sa.Column('max_num_batched_tokens', sa.Integer(), nullable=True),
    sa.Column('trust_remote_code', sa.Boolean(), nullable=False),
    sa.Column('internal_api_key', sa.String(length=128), nullable=True),
    sa.Column('internal_api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_exit_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serving_model_services_model_id'), 'serving_model_services', ['model_id'], unique=False)
    op.create_index(op.f('ix_serving_model_services_served_model_name'), 'serving_model_services', ['served_model_name'], unique=True)
    op.create_index(op.f('ix_serving_model_services_status'), 'serving_model_services', ['status'], unique=False)
    op.create_index(op.f('ix_serving_model_services_vllm_port'), 'serving_model_services', ['vllm_port'], unique=False)
    op.create_table('gateway_quota_buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('used_units', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['serving_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'scope', 'window_start', name='uq_gateway_quota_window')
    )
    op.create_index(op.f('ix_gateway_quota_buckets_api_key_id'), 'gateway_quota_buckets', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_gateway_quota_buckets_scope'), 'gateway_quota_buckets', ['scope'], unique=False)
    op.create_index(op.f('ix_gateway_quota_buckets_window_start'), 'gateway_quota_buckets', ['window_start'], unique=False)
    op.create_table('research_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('quarantine_path', sa.String(length=1024), nullable=True),
    sa.Column('parsed_text_path', sa.String(length=1024), nullable=True),
    sa.Column('source_locator', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['serving_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_files_api_key_id'), 'research_files', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_research_files_content_sha256'), 'research_files', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_research_files_expires_at'), 'research_files', ['expires_at'], unique=False)
    op.create_index(op.f('ix_research_files_status'), 'research_files', ['status'], unique=False)
    op.create_table('research_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=False),
    sa.Column('model_service_id', sa.String(length=36), nullable=True),
    sa.Column('served_model_name', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_ids', sa.JSON(), nullable=False),
    sa.Column('output_format', sa.String(length=16), nullable=False),
    sa.Column('require_citations', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('payload_path', sa.String(length=1024), nullable=True),
    sa.Column('result_path', sa.String(length=1024), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['serving_api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_service_id'], ['serving_model_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'served_model_name', 'idempotency_key', name='uq_research_job_api_model_idempotency')
    )
    op.create_index(op.f('ix_research_jobs_api_key_id'), 'research_jobs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_research_jobs_expires_at'), 'research_jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_research_jobs_idempotency_key'), 'research_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_research_jobs_lease_expires_at'), 'research_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_research_jobs_model_service_id'), 'research_jobs', ['model_service_id'], unique=False)
    op.create_index(op.f('ix_research_jobs_served_model_name'), 'research_jobs', ['served_model_name'], unique=False)
    op.create_index(op.f('ix_research_jobs_status'), 'research_jobs', ['status'], unique=False)
    op.create_table('serving_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_service_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_service_id'], ['serving_model_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serving_events_event_type'), 'serving_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_serving_events_model_service_id'), 'serving_events', ['model_service_id'], unique=False)
    op.create_table('serving_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('model_service_id', sa.String(length=36), nullable=True),
    sa.Column('served_model_name', sa.String(length=128), nullable=False),
    sa.Column('request_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['serving_api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_service_id'], ['serving_model_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serving_requests_api_key_id'), 'serving_requests', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_serving_requests_idempotency_key'), 'serving_requests', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_serving_requests_model_service_id'), 'serving_requests', ['model_service_id'], unique=False)
    op.create_index(op.f('ix_serving_requests_served_model_name'), 'serving_requests', ['served_model_name'], unique=False)
    op.create_index(op.f('ix_serving_requests_status'), 'serving_requests', ['status'], unique=False)
    op.create_table('research_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locator', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['serving_api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['research_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_chunks_api_key_id'), 'research_chunks', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_research_chunks_expires_at'), 'research_chunks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_research_chunks_file_id'), 'research_chunks', ['file_id'], unique=False)
    op.create_table('serving_usage_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('api_key_id', sa.String(length=36), nullable=True),
    sa.Column('model_service_id', sa.String(length=36), nullable=True),
    sa.Column('served_model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('usage_source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['serving_api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_service_id'], ['serving_model_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['serving_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serving_usage_records_api_key_id'), 'serving_usage_records', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_serving_usage_records_model_service_id'), 'serving_usage_records', ['model_service_id'], unique=False)
    op.create_index(op.f('ix_serving_usage_records_request_id'), 'serving_usage_records', ['request_id'], unique=False)
    op.create_index(op.f('ix_serving_usage_records_served_model_name'), 'serving_usage_records', ['served_model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serving_usage_records_served_model_name'), table_name='serving_usage_records')
    op.drop_index(op.f('ix_serving_usage_records_request_id'), table_name='serving_usage_records')
    op.drop_index(op.f('ix_serving_usage_records_model_service_id'), table_name='serving_usage_records')
    op.drop_index(op.f('ix_serving_usage_records_api_key_id'), table_name='serving_usage_records')
    op.drop_table('serving_usage_records')
    op.drop_index(op.f('ix_research_chunks_file_id'), table_name='research_chunks')
    op.drop_index(op.f('ix_research_chunks_expires_at'), table_name='research_chunks')
    op.drop_index(op.f('ix_research_chunks_api_key_id'), table_name='research_chunks')
    op.drop_table('research_chunks')
    op.drop_index(op.f('ix_serving_requests_status'), table_name='serving_requests')
    op.drop_index(op.f('ix_serving_requests_served_model_name'), table_name='serving_requests')
    op.drop_index(op.f('ix_serving_requests_model_service_id'), table_name='serving_requests')
    op.drop_index(op.f('ix_serving_requests_idempotency_key'), table_name='serving_requests')
    op.drop_index(op.f('ix_serving_requests_api_key_id'), table_name='serving_requests')
    op.drop_table('serving_requests')
    op.drop_index(op.f('ix_serving_events_model_service_id'), table_name='serving_events')
    op.drop_index(op.f('ix_serving_events_event_type'), table_name='serving_events')
    op.drop_table('serving_events')
    op.drop_index(op.f('ix_research_jobs_status'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_served_model_name'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_model_service_id'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_lease_expires_at'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_idempotency_key'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_expires_at'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_api_key_id'), table_name='research_jobs')
    op.drop_table('research_jobs')
    op.drop_index(op.f('ix_research_files_status'), table_name='research_files')
    op.drop_index(op.f('ix_research_files_expires_at'), table_name='research_files')
    op.drop_index(op.f('ix_research_files_content_sha256'), table_name='research_files')
    op.drop_index(op.f('ix_research_files_api_key_id'), table_name='research_files')
    op.drop_table('research_files')
    op.drop_index(op.f('ix_gateway_quota_buckets_window_start'), table_name='gateway_quota_buckets')
    op.drop_index(op.f('ix_gateway_quota_buckets_scope'), table_name='gateway_quota_buckets')
    op.drop_index(op.f('ix_gateway_quota_buckets_api_key_id'), table_name='gateway_quota_buckets')
    op.drop_table('gateway_quota_buckets')
    op.drop_index(op.f('ix_serving_model_services_vllm_port'), table_name='serving_model_services')
    op.drop_index(op.f('ix_serving_model_services_status'), table_name='serving_model_services')
    op.drop_index(op.f('ix_serving_model_services_served_model_name'), table_name='serving_model_services')
    op.drop_index(op.f('ix_serving_model_services_model_id'), table_name='serving_model_services')
    op.drop_table('serving_model_services')
    op.drop_index(op.f('ix_serving_api_keys_status'), table_name='serving_api_keys')
    op.drop_index(op.f('ix_serving_api_keys_key_hash'), table_name='serving_api_keys')
    op.drop_table('serving_api_keys')
    # ### end Alembic commands ###
